start-scheduler:
	yarn workspace @canvas-medical/embed-scheduler start

build-scheduler:
	yarn workspace @canvas-medical/embed-scheduler build

test-scheduler:
	yarn workspace @canvas-medical/embed-scheduler test

update-snapshots-scheduler:
	yarn workspace @canvas-medical/embed-scheduler test:update

start-appointments:
	yarn workspace @canvas-medical/embed-appointments start

build-appointments:
	yarn workspace @canvas-medical/embed-appointments build

test-appointments:
	yarn workspace @canvas-medical/embed-appointments test

update-snapshots-appointments:
	yarn workspace @canvas-medical/embed-appointments test:update

test-common:
	yarn workspace @canvas-medical/embed-common test

update-snapshots-common:
	yarn workspace @canvas-medical/embed-common test:update