AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - config.ru

Layout/LineLength:
  Max: 99

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/PredicateName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
