source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.5"

gem "rails", "~> 7.0.1"
gem "puma", "~> 5.0"

gem "oauth2"
gem "bootsnap", require: false

gem 'dotenv-rails', groups: [:development, :test]

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "simplecov", require: false
end

group :development do
  gem "web-console"
end
