source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.5"

gem "rails", "~> 7.0.1"
gem "puma", "~> 5.0"

gem "oauth2"
gem "bootsnap", require: false

gem 'redis'

gem "sentry-ruby"
gem "sentry-rails"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "simplecov", require: false
  gem "rubocop", "~> 1.8.1", require: false

  gem 'dotenv-rails'
end

group :development do
  gem "web-console"
end

group :test do
  gem 'vcr'
  gem 'webmock', require: false
end
