name: Publish
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        working-directory: ./clients
        run: yarn

      - name: Build Common
        working-directory: ./clients/common
        run: yarn build:esm

      - name: Build Appointments
        working-directory: ./clients/appointments
        run: yarn build:esm

      - name: Build Scheduler
        working-directory: ./clients/scheduler
        run: yarn build:esm

      - name: Publish Common
        working-directory: ./clients/common
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish Appointments
        working-directory: ./clients/appointments
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish Scheduler
        working-directory: ./clients/scheduler
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
