name: Test
on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
    # - name: Set Timezone
    #   uses: szenius/set-timezone@v1.0
    #   with:
    #     timezoneLinux: America/Denver

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ruby 2.7.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5

    - name: Cache ruby gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ubuntu-20-04-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ubuntu-20-04-gems-

    - name: Install ruby dependencies
      run: |
        cd proxy
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run specs
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        COVERAGE: '1'
        CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
        EMR_BASE_URL: https://training.canvasmedical.com
        FHIR_BASE_URL: https://fhir-training.canvasmedical.com
        API_KEY: realapikey
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd proxy
        bundle exec rspec

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage

  coverage:
    runs-on: ubuntu-latest
    needs: rspec

    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
        path: coverage

    - name: Check coverage
      uses: vigetlabs/simplecov-check@1.0
      with:
        minimum_coverage: 100
        coverage_path: coverage/.last_run.json
